"""FakeTestForgeClient — in-process pairwise reducer with no external dependencies."""

from __future__ import annotations

import itertools
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path

from app.burr_kit.testforge.backend_schemas import (
    RequestLog,
    ToolFeature,
    ToolStatus,
    ValidationError_,
    ValidationResult,
    ValidationWarning,
)
from app.burr_kit.parameter_space import ParameterModel, TestConstraint, TestParameter
from app.burr_kit.testforge.test_case_schemas import CoverageReport, TestCase, TestGenerationResult


# ---------------------------------------------------------------------------
# Constraint evaluation
# ---------------------------------------------------------------------------

def _eval_constraint(rule: str, values: dict[str, str]) -> bool:
    """Return True if *values* satisfies *rule* (i.e. does NOT violate it).

    Supported forms:
      - "IF <param> = <val> THEN <param2> != <val2>"
      - "IF <param> = <val> THEN <param2> = <val2>"
      - "<param> != <val>"  (standalone exclusion)
    """
    # Conditional: IF p1 = v1 THEN p2 != v2
    m = re.match(
        r"IF\s+(\w+)\s*=\s*(\S+)\s+THEN\s+(\w+)\s*!=\s*(\S+)",
        rule, re.IGNORECASE,
    )
    if m:
        cond_param, cond_val, excl_param, excl_val = m.group(1, 2, 3, 4)
        if values.get(cond_param) == cond_val and values.get(excl_param) == excl_val:
            return False
        return True

    # Conditional: IF p1 = v1 THEN p2 = v2
    m = re.match(
        r"IF\s+(\w+)\s*=\s*(\S+)\s+THEN\s+(\w+)\s*=\s*(\S+)",
        rule, re.IGNORECASE,
    )
    if m:
        cond_param, cond_val, req_param, req_val = m.group(1, 2, 3, 4)
        if values.get(cond_param) == cond_val and values.get(req_param) != req_val:
            return False
        return True

    # Standalone: param != val
    m = re.match(r"(\w+)\s*!=\s*(\S+)", rule)
    if m:
        param, val = m.group(1, 2)
        if values.get(param) == val:
            return False
        return True

    # Unknown rule form — assume satisfied (don't block generation)
    return True


def _filter_by_constraints(
    combos: list[tuple[str, ...]],
    names: list[str],
    constraints: list[TestConstraint],
) -> list[tuple[str, ...]]:
    """Remove combinations that violate any constraint."""
    return [
        combo for combo in combos
        if all(_eval_constraint(c.rule, dict(zip(names, combo))) for c in constraints)
    ]


class FakeTestForgeClient:
    """Returns a pairwise-reduced test set. No TNT dependency."""

    def __init__(self, log_dir: Path | None = None):
        self._log_dir = log_dir

    # -- interface methods --

    def validate_model(self, model: ParameterModel) -> ValidationResult:
        errors: list[ValidationError_] = []
        warnings: list[ValidationWarning] = []
        for p in model.parameters:
            if not p.name:
                errors.append(ValidationError_(parameter=p.name, message="Parameter name cannot be empty"))
            if len(p.values) < 1:
                errors.append(ValidationError_(parameter=p.name, message=f"Parameter '{p.name}' must have at least one value"))
            elif len(p.values) == 1:
                warnings.append(ValidationWarning(parameter=p.name, message=f"Parameter '{p.name}' has only one value — no combinatorial benefit"))
        if not model.parameters:
            errors.append(ValidationError_(message="No parameters defined"))
        return ValidationResult(valid=len(errors) == 0, errors=errors, warnings=warnings)

    def generate_test_suite(self, model: ParameterModel) -> TestGenerationResult:
        start = time.monotonic()
        params = model.parameters
        constraints = model.constraints

        if len(params) < 2:
            param = params[0]
            cases = [TestCase(id=i + 1, values={param.name: v}) for i, v in enumerate(param.values)]
            # Apply constraints to single-param case
            if constraints:
                cases = [c for c in cases if all(
                    _eval_constraint(con.rule, c.values) for con in constraints
                )]
        else:
            cases = self._pairwise(params, constraints)

        coverage = self._coverage(params, cases)
        elapsed = int((time.monotonic() - start) * 1000)

        # Build warning
        warnings: list[str] = ["Generated by FakeTestForgeClient (no TNT)"]
        if constraints and coverage.reduction_percentage < 0:
            warnings.append(f"Constraints removed some combinations; pairwise coverage may be incomplete")
        if constraints and len(cases) == 0:
            warnings.append("All combinations eliminated by constraints — no valid test cases")

        self._log("generate_test_suite", {"parameters": len(params)}, {
            "test_count": len(cases), "reduction": coverage.reduction_percentage,
        }, elapsed)

        return TestGenerationResult(
            test_cases=cases,
            coverage=coverage,
            execution_time=elapsed,
            warning="; ".join(warnings) if warnings else None,
        )

    def check_installation(self) -> ToolStatus:
        return ToolStatus(
            installed=True,
            name="FakeTestForgeClient",
            version="0.1.0",
            features=[
                ToolFeature(name="validate_model"),
                ToolFeature(name="generate_test_suite"),
                ToolFeature(name="calculate_coverage"),
            ],
            message="Fake backend — always available",
        )

    # -- pairwise algorithm (greedy, covers all value pairs) --

    @staticmethod
    def _pairwise(
        parameters: list[TestParameter],
        constraints: list[TestConstraint] | None = None,
    ) -> list[TestCase]:
        names = [p.name for p in parameters]
        value_lists = [p.values for p in parameters]
        constraints = constraints or []

        # Build uncovered pairs, but only include pairs that are achievable
        # under the given constraints.
        all_combos = list(itertools.product(*value_lists))
        if constraints:
            valid_combos = _filter_by_constraints(all_combos, names, constraints)
        else:
            valid_combos = all_combos

        uncovered: set[tuple[str, str, str, str]] = set()
        for combo in valid_combos:
            vals = dict(zip(names, combo))
            for i in range(len(names)):
                for j in range(i + 1, len(names)):
                    uncovered.add((names[i], vals[names[i]], names[j], vals[names[j]]))

        cases: list[TestCase] = []

        while uncovered:
            best: dict[str, str] | None = None
            best_count = 0
            for combo in valid_combos:
                vals = dict(zip(names, combo))
                count = sum(
                    1
                    for i in range(len(names))
                    for j in range(i + 1, len(names))
                    if (names[i], vals[names[i]], names[j], vals[names[j]]) in uncovered
                )
                if count > best_count:
                    best, best_count = vals, count
                if best_count == len(names) * (len(names) - 1) // 2:
                    break

            if best is None or best_count == 0:
                break

            for i in range(len(names)):
                for j in range(i + 1, len(names)):
                    uncovered.discard((names[i], best[names[i]], names[j], best[names[j]]))

            cases.append(TestCase(id=len(cases) + 1, values=best))

        return cases

    @staticmethod
    def _coverage(parameters: list[TestParameter], cases: list[TestCase]) -> CoverageReport:
        total = 1
        for p in parameters:
            total *= len(p.values)

        param_cov: dict[str, float] = {}
        for p in parameters:
            seen = {c.values.get(p.name) for c in cases}
            param_cov[p.name] = round(len(seen) / len(p.values) * 100, 1) if p.values else 0

        reduction = ((total - len(cases)) / total * 100) if total > 0 else 0
        return CoverageReport(
            total_combinations=total,
            generated_tests=len(cases),
            reduction_percentage=round(reduction, 1),
            coverage_level=2,
            parameter_coverage=param_cov,
        )

    # -- logging --

    def _log(self, method: str, request_body: dict, response_body: dict, duration_ms: int) -> None:
        if self._log_dir is None:
            return
        entry = RequestLog(
            timestamp=datetime.now(timezone.utc).isoformat(),
            method=method,
            endpoint=None,
            request_body=request_body,
            response_body=response_body,
            duration_ms=duration_ms,
            backend="fake",
        )
        self._log_dir.mkdir(parents=True, exist_ok=True)
        path = self._log_dir / "testforge_requests.jsonl"
        with path.open("a") as f:
            f.write(entry.model_dump_json() + "\n")
